#!/bin/sh

set -eu

echo "Running make rust-fmt..."
make rust-fmt

echo "Running make rust-clippy..."
make rust-clippy

echo "Running make rust-check..."
make rust-check

echo "Running make rust-doc..."
make rust-doc
