//! Unit tests for feature test collection helpers.

use std::fs;
use std::path::{Path, PathBuf};

use super::support::unique_temp_dir;
use crate::commands::collections::feature_tests::{
    discover_feature_test_scenarios, execute_feature_tests_with_runtime, run_features_test,
    FeatureTestRuntime,
};

const DEFAULT_FEATURE_TEST_BASE_IMAGE: &str = "docker.io/library/debian:bookworm-slim";

type ExecCall = (
    String,
    PathBuf,
    Option<String>,
    Vec<(String, String)>,
    String,
);

#[derive(Default)]
struct FakeFeatureTestRuntime {
    build_calls: Vec<(String, PathBuf, PathBuf)>,
    start_calls: Vec<(String, PathBuf)>,
    exec_calls: Vec<ExecCall>,
    remove_calls: Vec<String>,
    failure: Option<FakeRuntimeFailure>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum FakeRuntimeFailure {
    Build,
    Start,
    Exec,
    Remove,
}

impl FakeFeatureTestRuntime {
    fn failing(failure: FakeRuntimeFailure) -> Self {
        Self {
            failure: Some(failure),
            ..Self::default()
        }
    }
}

impl FeatureTestRuntime for FakeFeatureTestRuntime {
    fn build_image(
        &mut self,
        _args: &[String],
        image_name: &str,
        dockerfile_path: &Path,
        context_path: &Path,
    ) -> Result<(), String> {
        if self.failure == Some(FakeRuntimeFailure::Build) {
            return Err("fake build failed".to_string());
        }
        self.build_calls.push((
            image_name.to_string(),
            dockerfile_path.to_path_buf(),
            context_path.to_path_buf(),
        ));
        Ok(())
    }

    fn start_container(
        &mut self,
        _args: &[String],
        image_name: &str,
        workspace_dir: &Path,
    ) -> Result<String, String> {
        if self.failure == Some(FakeRuntimeFailure::Start) {
            return Err("fake start failed".to_string());
        }
        self.start_calls
            .push((image_name.to_string(), workspace_dir.to_path_buf()));
        Ok(format!("container-{}", self.start_calls.len()))
    }

    fn exec_script(
        &mut self,
        _args: &[String],
        container_id: &str,
        workspace_dir: &Path,
        remote_user: Option<&str>,
        env: &[(String, String)],
        script_name: &str,
    ) -> Result<i32, String> {
        if self.failure == Some(FakeRuntimeFailure::Exec) {
            return Err("fake exec failed".to_string());
        }
        self.exec_calls.push((
            container_id.to_string(),
            workspace_dir.to_path_buf(),
            remote_user.map(str::to_string),
            env.to_vec(),
            script_name.to_string(),
        ));
        Ok(if script_name == "failing.sh" { 1 } else { 0 })
    }

    fn remove_container(&mut self, _args: &[String], container_id: &str) -> Result<(), String> {
        if self.failure == Some(FakeRuntimeFailure::Remove) {
            return Err("fake remove failed".to_string());
        }
        self.remove_calls.push(container_id.to_string());
        Ok(())
    }
}

fn write_basic_feature_project() -> PathBuf {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    root
}

fn write_successful_engine(root: &Path) -> PathBuf {
    let engine = root.join("fake-engine");
    crate::test_support::write_executable_script(
        &engine,
        r#"#!/bin/sh
set -eu
command="$1"
shift
case "$command" in
  build)
    exit 0
    ;;
  run)
    echo "feature-test-container"
    exit 0
    ;;
  exec)
    exit 0
    ;;
  rm)
    exit 0
    ;;
  *)
    echo "unsupported command: $command" >&2
    exit 1
    ;;
esac
"#,
    );
    engine
}

fn write_failing_exec_engine(root: &Path) -> PathBuf {
    let engine = root.join("fake-engine");
    crate::test_support::write_executable_script(
        &engine,
        r#"#!/bin/sh
set -eu
command="$1"
shift
case "$command" in
  build)
    exit 0
    ;;
  run)
    echo "feature-test-container"
    exit 0
    ;;
  exec)
    exit 1
    ;;
  rm)
    exit 0
    ;;
  *)
    echo "unsupported command: $command" >&2
    exit 1
    ;;
esac
"#,
    );
    engine
}

#[test]
fn features_test_discovers_named_and_autogenerated_scenarios() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let global = root.join("test").join("_global");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::create_dir_all(&global).expect("global test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    fs::write(global.join("global-scenario.sh"), "#!/bin/sh\n").expect("global scenario script");
    fs::write(
        global.join("scenarios.json"),
        "{\n  \"global-scenario\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("global scenarios");

    let scenarios =
        discover_feature_test_scenarios(&[root.display().to_string()]).expect("scenario discovery");

    assert_eq!(scenarios, vec!["custom", "demo", "global-scenario"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_discovery_ignores_files_and_reports_missing_scenario_scripts() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test_root = root.join("test");
    let test = test_root.join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(test_root.join("README.md"), "not a scenario directory").expect("test root file");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("duplicate.sh"), "#!/bin/sh\n").expect("duplicate script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");

    let scenarios =
        discover_feature_test_scenarios(&[root.display().to_string()]).expect("scenario discovery");

    assert_eq!(
        scenarios,
        vec![
            "custom",
            "demo",
            "demo executed twice with randomized options"
        ]
    );

    fs::write(
        test.join("scenarios.json"),
        "{\n  \"missing-script\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    let error =
        discover_feature_test_scenarios(&[root.display().to_string()]).expect_err("missing script");

    assert!(
        error.contains("No scenario test script found at path"),
        "{error}"
    );
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_discovery_handles_non_object_scenarios_and_missing_test_root() {
    let root = unique_temp_dir();
    let test = root.join("test").join("demo");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(test.join("scenarios.json"), "[]").expect("scenarios");

    let scenarios =
        discover_feature_test_scenarios(&[root.display().to_string()]).expect("scenario discovery");

    assert!(scenarios.is_empty());
    let missing_root = unique_temp_dir();
    let missing_scenarios = discover_feature_test_scenarios(&[missing_root.display().to_string()])
        .expect("missing test root");
    assert!(missing_scenarios.is_empty());
    let _ = fs::remove_dir_all(root);
    let _ = fs::remove_dir_all(missing_root);
}

#[test]
fn features_test_discovery_defaults_to_current_project_folder() {
    let scenarios = discover_feature_test_scenarios(&[]).expect("default project folder");

    assert!(scenarios.is_empty());
}

#[test]
fn features_test_discovery_supports_project_folder_aliases_and_skip_flags() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let global = root.join("test").join("_global");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::create_dir_all(&global).expect("global test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("duplicate.sh"), "#!/bin/sh\n").expect("duplicate script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    fs::write(global.join("global.sh"), "#!/bin/sh\n").expect("global script");
    fs::write(
        global.join("scenarios.json"),
        "{\n  \"global\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("global scenarios");

    let skipped = discover_feature_test_scenarios(&[
        "--project-folder".to_string(),
        root.display().to_string(),
        "--skip-autogenerated".to_string(),
        "--skip-duplicated".to_string(),
    ])
    .expect("skip discovery");
    assert_eq!(skipped, vec!["custom", "global"]);

    let filtered = discover_feature_test_scenarios(&[
        "--projectFolder".to_string(),
        root.display().to_string(),
        "--features".to_string(),
        "demo".to_string(),
    ])
    .expect("feature filter discovery");
    assert_eq!(
        filtered,
        vec![
            "custom",
            "demo",
            "demo executed twice with randomized options"
        ]
    );
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_discovery_reports_invalid_scenarios_json() {
    let root = unique_temp_dir();
    let test = root.join("test").join("demo");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(test.join("scenarios.json"), "{").expect("invalid scenarios");

    let error =
        discover_feature_test_scenarios(&[root.display().to_string()]).expect_err("invalid json");

    assert!(!error.is_empty());
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_run_accepts_default_project_folder() {
    assert_eq!(run_features_test(&[]), std::process::ExitCode::SUCCESS);
}

#[test]
fn features_test_run_reports_discovery_errors() {
    let root = unique_temp_dir();
    let test = root.join("test").join("demo");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(test.join("scenarios.json"), "{").expect("invalid scenarios");

    assert_eq!(
        run_features_test(&["--project-folder".to_string(), root.display().to_string(),]),
        std::process::ExitCode::from(1)
    );

    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_run_executes_successfully_with_configured_engine() {
    let root = write_basic_feature_project();
    let engine = write_successful_engine(&root);

    let status = run_features_test(&[
        "--quiet".to_string(),
        "--docker-path".to_string(),
        engine.display().to_string(),
        root.display().to_string(),
    ]);

    assert_eq!(status, std::process::ExitCode::SUCCESS);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_run_reports_failed_script_exit_status() {
    let root = write_basic_feature_project();
    let engine = write_failing_exec_engine(&root);

    let status = run_features_test(&[
        "--docker-path".to_string(),
        engine.display().to_string(),
        root.display().to_string(),
    ]);

    assert_eq!(status, std::process::ExitCode::from(1));
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_run_accepts_short_quiet_with_no_cases() {
    let root = unique_temp_dir();
    fs::create_dir_all(&root).expect("project root");

    let status = run_features_test(&["-q".to_string(), root.display().to_string()]);

    assert_eq!(status, std::process::ExitCode::SUCCESS);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_global_scenarios_only_excludes_feature_scoped_cases() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let global = root.join("test").join("_global");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::create_dir_all(&global).expect("global test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    fs::write(global.join("global-scenario.sh"), "#!/bin/sh\n").expect("global scenario script");
    fs::write(
        global.join("scenarios.json"),
        "{\n  \"global-scenario\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("global scenarios");

    let scenarios = discover_feature_test_scenarios(&[
        "--global-scenarios-only".to_string(),
        root.display().to_string(),
    ])
    .expect("scenario discovery");

    assert_eq!(scenarios, vec!["global-scenario"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_skip_scenarios_keeps_autogenerated_cases_only() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let global = root.join("test").join("_global");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::create_dir_all(&global).expect("global test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    fs::write(global.join("global-scenario.sh"), "#!/bin/sh\n").expect("global scenario script");
    fs::write(
        global.join("scenarios.json"),
        "{\n  \"global-scenario\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("global scenarios");

    let scenarios = discover_feature_test_scenarios(&[
        "--skip-scenarios".to_string(),
        root.display().to_string(),
    ])
    .expect("scenario discovery");

    assert_eq!(scenarios, vec!["demo"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_filters_scenarios_after_feature_selection() {
    let root = unique_temp_dir();
    let demo_src = root.join("src").join("demo");
    let other_src = root.join("src").join("other");
    let demo_test = root.join("test").join("demo");
    let other_test = root.join("test").join("other");
    fs::create_dir_all(&demo_src).expect("demo feature src");
    fs::create_dir_all(&other_src).expect("other feature src");
    fs::create_dir_all(&demo_test).expect("demo feature test");
    fs::create_dir_all(&other_test).expect("other feature test");
    fs::write(
        demo_src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("demo manifest");
    fs::write(
        other_src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"other\",\n  \"name\": \"Other Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("other manifest");
    fs::write(demo_test.join("test.sh"), "#!/bin/sh\n").expect("demo test script");
    fs::write(demo_test.join("alpha.sh"), "#!/bin/sh\n").expect("alpha scenario script");
    fs::write(demo_test.join("beta.sh"), "#!/bin/sh\n").expect("beta scenario script");
    fs::write(
        demo_test.join("scenarios.json"),
        "{\n  \"alpha\": {\n    \"image\": \"ubuntu:latest\"\n  },\n  \"beta\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("demo scenarios");
    fs::write(other_test.join("test.sh"), "#!/bin/sh\n").expect("other test script");

    let scenarios = discover_feature_test_scenarios(&[
        "-f".to_string(),
        "demo".to_string(),
        "--filter".to_string(),
        "alp".to_string(),
        root.display().to_string(),
    ])
    .expect("scenario discovery");

    assert_eq!(scenarios, vec!["alpha"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_executes_scripts_inside_test_containers() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\",\n  \"options\": {\n    \"favorite\": {\n      \"type\": \"string\",\n      \"default\": \"blue\"\n    }\n  }\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    fs::write(test.join("failing.sh"), "#!/bin/sh\nexit 1\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"failing\": {\n    \"image\": \"ubuntu:latest\",\n    \"features\": {\n      \"demo\": {\n        \"favorite\": \"red\"\n      }\n    }\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 2);
    assert!(results
        .iter()
        .any(|result| result.name == "demo" && result.passed));
    assert!(results
        .iter()
        .any(|result| result.name == "failing" && !result.passed));
    assert_eq!(runtime.start_calls.len(), 2);
    assert_eq!(runtime.exec_calls[0].0, "container-1");
    assert_eq!(runtime.exec_calls[0].4, "test.sh");
    assert!(runtime.exec_calls[0]
        .1
        .join("dev-container-features-test-lib")
        .is_file());
    assert_eq!(runtime.exec_calls[1].4, "failing.sh");
    assert!(runtime.remove_calls.is_empty());
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_executes_with_requested_remote_user() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            "--remote-user".to_string(),
            "vscode".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    assert!(results[0].passed);
    assert_eq!(runtime.exec_calls.len(), 1);
    assert_eq!(runtime.exec_calls[0].2.as_deref(), Some("vscode"));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_executes_with_project_folder_alias() {
    let root = write_basic_feature_project();
    let mut runtime = FakeFeatureTestRuntime::default();

    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            "--projectFolder".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    assert!(results[0].passed);
    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_defaults_per_feature_scenarios_to_enclosing_feature() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 2);
    assert!(results
        .iter()
        .any(|result| result.name == "demo" && result.passed));
    assert!(results
        .iter()
        .any(|result| result.name == "custom" && result.passed));
    assert!(runtime
        .build_calls
        .iter()
        .map(|(_, _, context_path)| context_path.join("feature-0-demo").join("install.sh"))
        .any(|install_path| install_path.is_file()));
    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_uses_repo_default_base_image_without_override() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");

    let mut runtime = FakeFeatureTestRuntime::default();
    execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    let dockerfiles = runtime
        .build_calls
        .iter()
        .map(|(_, dockerfile_path, _)| {
            fs::read_to_string(dockerfile_path).expect("dockerfile contents")
        })
        .collect::<Vec<_>>();
    assert!(dockerfiles
        .iter()
        .any(|dockerfile| dockerfile.contains(&format!("FROM {DEFAULT_FEATURE_TEST_BASE_IMAGE}"))));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_builds_scenario_base_images() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let scenario_dir = test.join("custom");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&scenario_dir).expect("scenario dir");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(scenario_dir.join("Dockerfile.base"), "FROM scratch\n").expect("base dockerfile");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"build\": {\n      \"dockerfile\": \"Dockerfile.base\",\n      \"context\": \".\"\n    }\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    assert!(results[0].passed);
    assert_eq!(runtime.build_calls.len(), 2);
    assert!(runtime.build_calls[0]
        .1
        .ends_with(Path::new("custom").join("Dockerfile.base")));
    assert!(runtime.build_calls[0].2.ends_with("custom"));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_propagates_runtime_failures() {
    for (failure, expected) in [
        (FakeRuntimeFailure::Build, "fake build failed"),
        (FakeRuntimeFailure::Start, "fake start failed"),
        (FakeRuntimeFailure::Exec, "fake exec failed"),
        (FakeRuntimeFailure::Remove, "fake remove failed"),
    ] {
        let root = write_basic_feature_project();
        let mut runtime = FakeFeatureTestRuntime::failing(failure);

        let error = execute_feature_tests_with_runtime(&[root.display().to_string()], &mut runtime)
            .expect_err("runtime failure");

        assert_eq!(error, expected);
        for (_, workspace_dir) in &runtime.start_calls {
            let _ = fs::remove_dir_all(workspace_dir);
        }
        let _ = fs::remove_dir_all(root);
    }
}

#[test]
fn features_test_reports_missing_autogenerated_feature_sources() {
    let root = unique_temp_dir();
    let test = root.join("test").join("demo");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    let mut runtime = FakeFeatureTestRuntime::default();

    let error = execute_feature_tests_with_runtime(&[root.display().to_string()], &mut runtime)
        .expect_err("missing feature source");

    assert!(
        error.contains("Feature source directory not found at"),
        "{error}"
    );
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_reports_scenario_feature_installation_errors() {
    let root = unique_temp_dir();
    let test = root.join("test").join("demo");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(test.join("custom.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"features\": {\n      \"./demo\": {}\n    }\n  }\n}\n",
    )
    .expect("scenarios");
    let mut runtime = FakeFeatureTestRuntime::default();

    let error = execute_feature_tests_with_runtime(&[root.display().to_string()], &mut runtime)
        .expect_err("scenario feature error");

    assert_eq!(
        error,
        "Unsupported relative feature in test scenario: ./demo"
    );
    let _ = fs::remove_dir_all(root);
}

#[cfg(unix)]
#[test]
fn features_test_reports_feature_materialization_failures() {
    let root = write_basic_feature_project();
    let broken_link = root.join("src").join("demo").join("broken-link");
    std::os::unix::fs::symlink(root.join("missing-target"), &broken_link).expect("broken symlink");
    let mut runtime = FakeFeatureTestRuntime::default();

    let error = execute_feature_tests_with_runtime(&[root.display().to_string()], &mut runtime)
        .expect_err("materialization error");

    assert!(!error.is_empty());
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_accepts_published_feature_dependencies_in_scenarios() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    fs::write(test.join("dependency.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"dependency\": {\n    \"image\": \"ubuntu:latest\",\n    \"features\": {\n      \"ghcr.io/devcontainers/features/common-utils:1\": {},\n      \"demo\": {}\n    }\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 2);
    assert!(results
        .iter()
        .any(|result| result.name == "dependency" && result.passed));
    let dockerfiles = runtime
        .build_calls
        .iter()
        .map(|(_, dockerfile_path, _)| {
            fs::read_to_string(dockerfile_path).expect("dockerfile contents")
        })
        .collect::<Vec<_>>();
    assert!(dockerfiles
        .iter()
        .any(|dockerfile| dockerfile.contains("common-utils")));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_duplicate_cases_accept_permit_randomization() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\",\n  \"options\": {\n    \"color\": {\n      \"type\": \"string\",\n      \"enum\": [\"blue\", \"green\", \"red\"],\n      \"default\": \"blue\"\n    }\n  }\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("duplicate.sh"), "#!/bin/sh\nexit 0\n").expect("duplicate script");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            "--permit-randomization".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    let duplicate_exec = runtime
        .exec_calls
        .iter()
        .find(|call| call.4 == "duplicate.sh")
        .expect("duplicate exec call");
    let color = duplicate_exec
        .3
        .iter()
        .find(|(key, _)| key == "COLOR")
        .map(|(_, value)| value.as_str())
        .expect("duplicate env");
    assert_ne!(color, "blue");

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}
