//! Unit tests for feature test collection helpers.

use std::fs;
use std::path::{Path, PathBuf};

use super::support::unique_temp_dir;
use crate::commands::collections::feature_tests::{
    discover_feature_test_scenarios, execute_feature_tests_with_runtime, FeatureTestRuntime,
};

const DEFAULT_FEATURE_TEST_BASE_IMAGE: &str = "docker.io/library/debian:bookworm-slim";

type ExecCall = (
    String,
    PathBuf,
    Option<String>,
    Vec<(String, String)>,
    String,
);

#[derive(Default)]
struct FakeFeatureTestRuntime {
    build_calls: Vec<(String, PathBuf, PathBuf)>,
    start_calls: Vec<(String, PathBuf)>,
    exec_calls: Vec<ExecCall>,
    remove_calls: Vec<String>,
}

impl FeatureTestRuntime for FakeFeatureTestRuntime {
    fn build_image(
        &mut self,
        _args: &[String],
        image_name: &str,
        dockerfile_path: &Path,
        context_path: &Path,
    ) -> Result<(), String> {
        self.build_calls.push((
            image_name.to_string(),
            dockerfile_path.to_path_buf(),
            context_path.to_path_buf(),
        ));
        Ok(())
    }

    fn start_container(
        &mut self,
        _args: &[String],
        image_name: &str,
        workspace_dir: &Path,
    ) -> Result<String, String> {
        self.start_calls
            .push((image_name.to_string(), workspace_dir.to_path_buf()));
        Ok(format!("container-{}", self.start_calls.len()))
    }

    fn exec_script(
        &mut self,
        _args: &[String],
        container_id: &str,
        workspace_dir: &Path,
        remote_user: Option<&str>,
        env: &[(String, String)],
        script_name: &str,
    ) -> Result<i32, String> {
        self.exec_calls.push((
            container_id.to_string(),
            workspace_dir.to_path_buf(),
            remote_user.map(str::to_string),
            env.to_vec(),
            script_name.to_string(),
        ));
        Ok(if script_name == "failing.sh" { 1 } else { 0 })
    }

    fn remove_container(&mut self, _args: &[String], container_id: &str) -> Result<(), String> {
        self.remove_calls.push(container_id.to_string());
        Ok(())
    }
}

#[test]
fn features_test_discovers_named_and_autogenerated_scenarios() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let global = root.join("test").join("_global");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::create_dir_all(&global).expect("global test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    fs::write(global.join("global-scenario.sh"), "#!/bin/sh\n").expect("global scenario script");
    fs::write(
        global.join("scenarios.json"),
        "{\n  \"global-scenario\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("global scenarios");

    let scenarios =
        discover_feature_test_scenarios(&[root.display().to_string()]).expect("scenario discovery");

    assert_eq!(scenarios, vec!["custom", "demo", "global-scenario"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_global_scenarios_only_excludes_feature_scoped_cases() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    let global = root.join("test").join("_global");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::create_dir_all(&global).expect("global test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(test.join("test.sh"), "#!/bin/sh\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");
    fs::write(global.join("global-scenario.sh"), "#!/bin/sh\n").expect("global scenario script");
    fs::write(
        global.join("scenarios.json"),
        "{\n  \"global-scenario\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("global scenarios");

    let scenarios = discover_feature_test_scenarios(&[
        "--global-scenarios-only".to_string(),
        root.display().to_string(),
    ])
    .expect("scenario discovery");

    assert_eq!(scenarios, vec!["global-scenario"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_filters_scenarios_after_feature_selection() {
    let root = unique_temp_dir();
    let demo_src = root.join("src").join("demo");
    let other_src = root.join("src").join("other");
    let demo_test = root.join("test").join("demo");
    let other_test = root.join("test").join("other");
    fs::create_dir_all(&demo_src).expect("demo feature src");
    fs::create_dir_all(&other_src).expect("other feature src");
    fs::create_dir_all(&demo_test).expect("demo feature test");
    fs::create_dir_all(&other_test).expect("other feature test");
    fs::write(
        demo_src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("demo manifest");
    fs::write(
        other_src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"other\",\n  \"name\": \"Other Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("other manifest");
    fs::write(demo_test.join("test.sh"), "#!/bin/sh\n").expect("demo test script");
    fs::write(demo_test.join("alpha.sh"), "#!/bin/sh\n").expect("alpha scenario script");
    fs::write(demo_test.join("beta.sh"), "#!/bin/sh\n").expect("beta scenario script");
    fs::write(
        demo_test.join("scenarios.json"),
        "{\n  \"alpha\": {\n    \"image\": \"ubuntu:latest\"\n  },\n  \"beta\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("demo scenarios");
    fs::write(other_test.join("test.sh"), "#!/bin/sh\n").expect("other test script");

    let scenarios = discover_feature_test_scenarios(&[
        "-f".to_string(),
        "demo".to_string(),
        "--filter".to_string(),
        "alp".to_string(),
        root.display().to_string(),
    ])
    .expect("scenario discovery");

    assert_eq!(scenarios, vec!["alpha"]);
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_executes_scripts_inside_test_containers() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\",\n  \"options\": {\n    \"favorite\": {\n      \"type\": \"string\",\n      \"default\": \"blue\"\n    }\n  }\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    fs::write(test.join("failing.sh"), "#!/bin/sh\nexit 1\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"failing\": {\n    \"image\": \"ubuntu:latest\",\n    \"features\": {\n      \"demo\": {\n        \"favorite\": \"red\"\n      }\n    }\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 2);
    assert!(results
        .iter()
        .any(|result| result.name == "demo" && result.passed));
    assert!(results
        .iter()
        .any(|result| result.name == "failing" && !result.passed));
    assert_eq!(runtime.start_calls.len(), 2);
    assert_eq!(runtime.exec_calls[0].0, "container-1");
    assert_eq!(runtime.exec_calls[0].4, "test.sh");
    assert!(runtime.exec_calls[0]
        .1
        .join("dev-container-features-test-lib")
        .is_file());
    assert_eq!(runtime.exec_calls[1].4, "failing.sh");
    assert!(runtime.remove_calls.is_empty());
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_executes_with_requested_remote_user() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            "--remote-user".to_string(),
            "vscode".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    assert!(results[0].passed);
    assert_eq!(runtime.exec_calls.len(), 1);
    assert_eq!(runtime.exec_calls[0].2.as_deref(), Some("vscode"));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_defaults_per_feature_scenarios_to_enclosing_feature() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"image\": \"ubuntu:latest\"\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 2);
    assert!(results
        .iter()
        .any(|result| result.name == "demo" && result.passed));
    assert!(results
        .iter()
        .any(|result| result.name == "custom" && result.passed));
    assert!(runtime
        .build_calls
        .iter()
        .map(|(_, _, context_path)| context_path.join("feature-0-demo").join("install.sh"))
        .any(|install_path| install_path.is_file()));
    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_uses_repo_default_base_image_without_override() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");

    let mut runtime = FakeFeatureTestRuntime::default();
    execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    let dockerfiles = runtime
        .build_calls
        .iter()
        .map(|(_, dockerfile_path, _)| {
            fs::read_to_string(dockerfile_path).expect("dockerfile contents")
        })
        .collect::<Vec<_>>();
    assert!(dockerfiles
        .iter()
        .any(|dockerfile| dockerfile.contains(&format!("FROM {DEFAULT_FEATURE_TEST_BASE_IMAGE}"))));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_accepts_published_feature_dependencies_in_scenarios() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("test.sh"), "#!/bin/sh\nexit 0\n").expect("test script");
    fs::write(test.join("dependency.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"dependency\": {\n    \"image\": \"ubuntu:latest\",\n    \"features\": {\n      \"ghcr.io/devcontainers/features/common-utils:1\": {},\n      \"demo\": {}\n    }\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 2);
    assert!(results
        .iter()
        .any(|result| result.name == "dependency" && result.passed));
    let dockerfiles = runtime
        .build_calls
        .iter()
        .map(|(_, dockerfile_path, _)| {
            fs::read_to_string(dockerfile_path).expect("dockerfile contents")
        })
        .collect::<Vec<_>>();
    assert!(dockerfiles
        .iter()
        .any(|dockerfile| dockerfile.contains("common-utils")));

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_builds_scenario_base_images_before_feature_layers() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\"\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("custom.sh"), "#!/bin/sh\nexit 0\n").expect("scenario script");
    fs::write(test.join("Dockerfile"), "FROM alpine:3.20\n").expect("scenario dockerfile");
    fs::write(
        test.join("scenarios.json"),
        "{\n  \"custom\": {\n    \"build\": {\n      \"dockerfile\": \"Dockerfile\",\n      \"context\": \".\"\n    },\n    \"features\": {\n      \"demo\": {}\n    }\n  }\n}\n",
    )
    .expect("scenarios");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    assert!(results[0].passed);
    assert_eq!(runtime.build_calls.len(), 2);
    assert!(runtime.build_calls[0]
        .1
        .file_name()
        .and_then(|value| value.to_str())
        .is_some_and(|name| name == "Dockerfile"));
    assert_eq!(
        fs::read_to_string(runtime.build_calls[0].2.join("Dockerfile")).expect("copied dockerfile"),
        "FROM alpine:3.20\n"
    );
    assert!(runtime.build_calls[1]
        .0
        .starts_with("devcontainer-feature-test-"));
    let _ = fs::remove_dir_all(root);
}

#[test]
fn features_test_duplicate_cases_accept_permit_randomization() {
    let root = unique_temp_dir();
    let src = root.join("src").join("demo");
    let test = root.join("test").join("demo");
    fs::create_dir_all(&src).expect("feature src");
    fs::create_dir_all(&test).expect("feature test");
    fs::write(
        src.join("devcontainer-feature.json"),
        "{\n  \"id\": \"demo\",\n  \"name\": \"Demo Feature\",\n  \"version\": \"1.0.0\",\n  \"options\": {\n    \"color\": {\n      \"type\": \"string\",\n      \"enum\": [\"blue\", \"green\", \"red\"],\n      \"default\": \"blue\"\n    }\n  }\n}\n",
    )
    .expect("manifest");
    fs::write(src.join("install.sh"), "#!/bin/sh\nexit 0\n").expect("install script");
    fs::write(test.join("duplicate.sh"), "#!/bin/sh\nexit 0\n").expect("duplicate script");

    let mut runtime = FakeFeatureTestRuntime::default();
    let results = execute_feature_tests_with_runtime(
        &[
            "--preserve-test-containers".to_string(),
            "--permit-randomization".to_string(),
            root.display().to_string(),
        ],
        &mut runtime,
    )
    .expect("test execution");

    assert_eq!(results.len(), 1);
    let duplicate_exec = runtime
        .exec_calls
        .iter()
        .find(|call| call.4 == "duplicate.sh")
        .expect("duplicate exec call");
    let color = duplicate_exec
        .3
        .iter()
        .find(|(key, _)| key == "COLOR")
        .map(|(_, value)| value.as_str())
        .expect("duplicate env");
    assert_ne!(color, "blue");

    for (_, workspace_dir) in &runtime.start_calls {
        let _ = fs::remove_dir_all(workspace_dir);
    }
    let _ = fs::remove_dir_all(root);
}
