//! Feature test discovery helpers for collection commands.

use std::fs;
use std::path::Path;

use serde_json::{Map, Value};

use super::materialize::{
    duplicate_feature_option_values, feature_installation, scenario_base_image,
    scenario_feature_installations, unique_feature_test_dir,
};
use super::{
    BaseImageSource, FeatureInstallation, FeatureInstallationSource, FeatureTestCase,
    FeatureTestExecution, FeatureTestOptions, PreparedFeatureTestCase, FEATURE_TEST_LIBRARY_SCRIPT,
    FEATURE_TEST_LIBRARY_SCRIPT_NAME,
};
use crate::commands::common;

pub(super) fn discover_feature_test_cases(args: &[String]) -> Result<Vec<FeatureTestCase>, String> {
    let project_folder = match feature_test_project_folder_arg(args) {
        Some(project_folder) => project_folder,
        None => return Err("features test requires a project folder".to_string()),
    };
    let filter = common::parse_option_value(args, "--filter");
    let feature_filter = feature_filter_arg(args);
    let skip_scenarios = common::has_flag(args, "--skip-scenarios");
    let global_scenarios_only = common::has_flag(args, "--global-scenarios-only");
    let skip_autogenerated = common::has_flag(args, "--skip-autogenerated");
    let skip_duplicated = common::has_flag(args, "--skip-duplicated");
    let test_root = std::path::Path::new(&project_folder).join("test");
    let mut cases = Vec::new();

    let entries = match fs::read_dir(&test_root) {
        Ok(entries) => entries,
        Err(_) => return Ok(Vec::new()),
    };
    for entry in entries {
        let entry = entry.map_err(|error| error.to_string())?;
        let entry_path = entry.path();
        if !entry_path.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if name == "_global" {
            if feature_filter.is_some() || skip_scenarios {
                continue;
            }
            let scenarios = load_named_scenarios(&entry_path)?;
            cases.extend(scenarios);
            continue;
        }
        if global_scenarios_only {
            continue;
        }
        if feature_filter_excludes(&feature_filter, &name) {
            continue;
        }
        if entry_path.join("test.sh").is_file() && !skip_autogenerated {
            cases.push(FeatureTestCase {
                name: name.clone(),
                script_path: entry_path.join("test.sh"),
                execution: FeatureTestExecution::Autogenerated {
                    feature: name.clone(),
                },
            });
        }
        if entry_path.join("duplicate.sh").is_file() && !skip_duplicated {
            cases.push(FeatureTestCase {
                name: format!("{name} executed twice with randomized options"),
                script_path: entry_path.join("duplicate.sh"),
                execution: FeatureTestExecution::Duplicate {
                    feature: name.clone(),
                },
            });
        }
        if skip_scenarios {
            continue;
        }
        let scenarios = load_named_scenarios(&entry_path)?;
        cases.extend(scenarios);
    }

    cases.sort_by(|left, right| left.name.cmp(&right.name));
    cases.dedup_by(|left, right| left.name == right.name);
    if let Some(filter) = filter {
        let mut filtered = Vec::new();
        for scenario in cases {
            if scenario.name.contains(&filter) {
                filtered.push(scenario);
            }
        }
        cases = filtered;
    }
    Ok(cases)
}

fn feature_test_project_folder_arg(args: &[String]) -> Option<String> {
    if let Some(project_folder) = common::parse_option_value(args, "--project-folder") {
        return Some(project_folder);
    }
    if let Some(project_folder) = common::parse_option_value(args, "--projectFolder") {
        return Some(project_folder);
    }
    for arg in args.iter().rev() {
        if !arg.starts_with('-') {
            return Some(arg.clone());
        }
    }
    None
}

fn feature_filter_arg(args: &[String]) -> Option<String> {
    match common::parse_option_value(args, "-f") {
        Some(feature_filter) => Some(feature_filter),
        None => common::parse_option_value(args, "--features"),
    }
}

fn feature_filter_excludes(feature_filter: &Option<String>, feature_name: &str) -> bool {
    match feature_filter.as_deref() {
        Some(filter) => filter != feature_name,
        None => false,
    }
}

fn load_named_scenarios(test_dir: &Path) -> Result<Vec<FeatureTestCase>, String> {
    let scenarios_path = test_dir.join("scenarios.json");
    if !scenarios_path.is_file() {
        return Ok(Vec::new());
    }
    let raw = fs::read_to_string(scenarios_path).map_err(|error| error.to_string())?;
    let parsed = crate::config::parse_jsonc_value(&raw)?;
    let Some(entries) = parsed.as_object() else {
        return Ok(Vec::new());
    };
    let mut cases = Vec::with_capacity(entries.len());
    for (name, config) in entries {
        let script_path = test_dir.join(format!("{name}.sh"));
        if !script_path.is_file() {
            return Err(format!(
                "No scenario test script found at path '{}'",
                script_path.display()
            ));
        }
        cases.push(FeatureTestCase {
            name: name.clone(),
            script_path,
            execution: FeatureTestExecution::Scenario {
                scenario_dir: name.clone(),
                config: config.clone(),
            },
        });
    }
    Ok(cases)
}

pub(super) fn prepare_feature_test_case(
    options: &FeatureTestOptions,
    case: &FeatureTestCase,
) -> Result<PreparedFeatureTestCase, String> {
    prepare_feature_test_case_in_workspace(options, case, unique_feature_test_dir())
}

fn prepare_feature_test_case_in_workspace(
    options: &FeatureTestOptions,
    case: &FeatureTestCase,
    workspace_dir: std::path::PathBuf,
) -> Result<PreparedFeatureTestCase, String> {
    fs::create_dir_all(&workspace_dir).map_err(|error| error.to_string())?;
    let test_dir = match case.script_path.parent() {
        Some(test_dir) => test_dir,
        None => {
            return Err(format!(
                "Invalid test script path: {}",
                case.script_path.display()
            ))
        }
    };
    common::copy_directory_recursive(test_dir, &workspace_dir)?;
    fs::write(
        workspace_dir.join(FEATURE_TEST_LIBRARY_SCRIPT_NAME),
        FEATURE_TEST_LIBRARY_SCRIPT,
    )
    .map_err(|error| error.to_string())?;
    let script_name = match case
        .script_path
        .file_name()
        .and_then(|value| value.to_str())
    {
        Some(script_name) => script_name.to_string(),
        None => {
            return Err(format!(
                "Invalid test script path: {}",
                case.script_path.display()
            ))
        }
    };
    let build_context_dir = workspace_dir.join(".feature-test-build");
    fs::create_dir_all(&build_context_dir).map_err(|error| error.to_string())?;

    let (base_image, feature_installations, exec_env) = match &case.execution {
        FeatureTestExecution::Autogenerated { feature } => (
            BaseImageSource::Image(options.base_image.clone()),
            vec![feature_installation(
                &options.project_folder.join("src").join(feature),
                &Value::Object(Map::new()),
            )?],
            Vec::new(),
        ),
        FeatureTestExecution::Scenario {
            scenario_dir,
            config,
        } => (
            scenario_base_image(options, scenario_dir, config, &workspace_dir),
            scenario_feature_installations(
                &options.project_folder,
                case.script_path
                    .parent()
                    .and_then(|path| path.file_name())
                    .and_then(|value| value.to_str())
                    .filter(|value| *value != "_global"),
                config,
            )?,
            Vec::new(),
        ),
        FeatureTestExecution::Duplicate { feature } => {
            let feature_dir = options.project_folder.join("src").join(feature);
            let (default_options, alternate_options) =
                duplicate_feature_option_values(&feature_dir, options.permit_randomization)?;
            let mut exec_env = alternate_options.clone();
            for (key, value) in &default_options {
                exec_env.push((format!("{key}__DEFAULT"), value.clone()));
            }
            (
                BaseImageSource::Image(options.base_image.clone()),
                vec![
                    FeatureInstallation {
                        source: FeatureInstallationSource::Local(feature_dir.clone()),
                        env: alternate_options.clone(),
                    },
                    FeatureInstallation {
                        source: FeatureInstallationSource::Local(feature_dir),
                        env: default_options,
                    },
                ],
                exec_env,
            )
        }
    };

    Ok(PreparedFeatureTestCase {
        name: case.name.clone(),
        workspace_dir,
        build_context_dir,
        base_image,
        script_name,
        feature_installations,
        exec_env,
        remote_user: options.remote_user.clone(),
    })
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;

    use serde_json::Value;

    use super::{
        discover_feature_test_cases, feature_filter_arg, feature_filter_excludes,
        feature_test_project_folder_arg, prepare_feature_test_case,
        prepare_feature_test_case_in_workspace, FeatureTestCase, FeatureTestExecution,
        FEATURE_TEST_LIBRARY_SCRIPT_NAME,
    };
    use crate::commands::collections::feature_tests::{
        BaseImageSource, FeatureInstallationSource, FeatureTestOptions,
    };

    fn test_options(project_folder: PathBuf) -> FeatureTestOptions {
        FeatureTestOptions {
            project_folder,
            base_image: "debian:bookworm-slim".to_string(),
            remote_user: None,
            preserve_test_containers: false,
            permit_randomization: false,
            quiet: true,
        }
    }

    #[test]
    fn prepare_feature_test_case_reports_paths_without_parent_directory() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let case = FeatureTestCase {
            name: "invalid".to_string(),
            script_path: PathBuf::from("/"),
            execution: FeatureTestExecution::Scenario {
                scenario_dir: "invalid".to_string(),
                config: Value::Object(Default::default()),
            },
        };

        let error = prepare_feature_test_case(&test_options(root.clone()), &case)
            .expect_err("invalid path");

        assert!(error.contains("Invalid test script path: /"), "{error}");
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn feature_test_project_folder_arg_uses_trailing_positionals() {
        let args = vec!["--quiet".to_string(), "/workspace/project".to_string()];

        assert_eq!(
            feature_test_project_folder_arg(&args).as_deref(),
            Some("/workspace/project")
        );
        assert_eq!(
            feature_test_project_folder_arg(&["--quiet".to_string()]),
            None
        );
    }

    #[test]
    fn feature_filter_arg_prefers_short_flag_and_exclusion_matches_names() {
        let args = vec![
            "--features".to_string(),
            "from-long".to_string(),
            "-f".to_string(),
            "from-short".to_string(),
        ];
        let long_only = vec!["--features".to_string(), "from-long".to_string()];

        assert_eq!(feature_filter_arg(&args).as_deref(), Some("from-short"));
        assert_eq!(feature_filter_arg(&long_only).as_deref(), Some("from-long"));
        assert_eq!(feature_filter_arg(&[]), None);
        assert!(!feature_filter_excludes(&Some("demo".to_string()), "demo"));
        assert!(feature_filter_excludes(&Some("other".to_string()), "demo"));
        assert!(!feature_filter_excludes(&None, "demo"));
    }

    #[test]
    fn discover_feature_test_cases_reports_global_missing_scenario_scripts() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let global = root.join("test").join("_global");
        fs::create_dir_all(&global).expect("global test dir");
        fs::write(
            global.join("scenarios.json"),
            r#"{
  "missing": {
    "image": "ubuntu:latest"
  }
}"#,
        )
        .expect("scenarios");

        let error =
            discover_feature_test_cases(&[root.display().to_string()]).expect_err("missing script");

        assert!(
            error.contains("No scenario test script found at path"),
            "{error}"
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn discover_feature_test_cases_applies_skip_and_feature_filters() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let feature = root.join("test").join("demo");
        let global = root.join("test").join("_global");
        fs::create_dir_all(&feature).expect("feature test dir");
        fs::create_dir_all(&global).expect("global test dir");
        fs::write(feature.join("test.sh"), "#!/bin/sh\n").expect("test script");
        fs::write(feature.join("duplicate.sh"), "#!/bin/sh\n").expect("duplicate script");
        fs::write(feature.join("custom.sh"), "#!/bin/sh\n").expect("scenario script");
        fs::write(
            feature.join("scenarios.json"),
            r#"{
  "custom": {
    "image": "ubuntu:latest"
  }
}"#,
        )
        .expect("scenarios");
        fs::write(global.join("global.sh"), "#!/bin/sh\n").expect("global script");
        fs::write(
            global.join("scenarios.json"),
            r#"{
  "global": {
    "image": "ubuntu:latest"
  }
}"#,
        )
        .expect("global scenarios");

        let skip_scenarios = discover_feature_test_cases(&[
            "--skip-scenarios".to_string(),
            root.display().to_string(),
        ])
        .expect("skip scenarios");
        assert_eq!(
            skip_scenarios
                .iter()
                .map(|case| case.name.as_str())
                .collect::<Vec<_>>(),
            vec!["demo", "demo executed twice with randomized options"]
        );

        let feature_filtered = discover_feature_test_cases(&[
            "--features".to_string(),
            "other".to_string(),
            root.display().to_string(),
        ])
        .expect("feature filtered");
        assert!(feature_filtered.is_empty());

        let skip_generated = discover_feature_test_cases(&[
            "--skip-autogenerated".to_string(),
            "--skip-duplicated".to_string(),
            root.display().to_string(),
        ])
        .expect("skip generated");
        assert_eq!(
            skip_generated
                .iter()
                .map(|case| case.name.as_str())
                .collect::<Vec<_>>(),
            vec!["custom", "global"]
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn prepare_feature_test_case_reports_copy_errors() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let blocked_parent = root.join("blocked");
        fs::create_dir_all(&root).expect("root");
        fs::write(&blocked_parent, "not a directory").expect("blocked parent");
        let case = FeatureTestCase {
            name: "blocked".to_string(),
            script_path: blocked_parent.join("test.sh"),
            execution: FeatureTestExecution::Autogenerated {
                feature: "demo".to_string(),
            },
        };

        let error = prepare_feature_test_case(&test_options(root.clone()), &case)
            .expect_err("copy should fail");

        assert!(!error.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn prepare_feature_test_case_reports_workspace_create_errors() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let test_dir = root.join("test").join("demo");
        let blocked_parent = root.join("blocked");
        fs::create_dir_all(&test_dir).expect("test dir");
        fs::write(test_dir.join("test.sh"), "#!/bin/sh\n").expect("script");
        fs::write(&blocked_parent, "not a directory").expect("blocked parent");
        let case = FeatureTestCase {
            name: "demo".to_string(),
            script_path: test_dir.join("test.sh"),
            execution: FeatureTestExecution::Autogenerated {
                feature: "demo".to_string(),
            },
        };

        let error = prepare_feature_test_case_in_workspace(
            &test_options(root.clone()),
            &case,
            blocked_parent.join("workspace"),
        )
        .expect_err("workspace create should fail");

        assert!(!error.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn prepare_feature_test_case_reports_library_write_errors() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let workspace = crate::test_support::unique_temp_dir("feature-test-discovery-workspace");
        let test_dir = root.join("test").join("demo");
        fs::create_dir_all(&test_dir).expect("test dir");
        fs::create_dir_all(workspace.join(FEATURE_TEST_LIBRARY_SCRIPT_NAME))
            .expect("blocked library path");
        fs::write(test_dir.join("test.sh"), "#!/bin/sh\n").expect("script");
        let case = FeatureTestCase {
            name: "demo".to_string(),
            script_path: test_dir.join("test.sh"),
            execution: FeatureTestExecution::Autogenerated {
                feature: "demo".to_string(),
            },
        };

        let error = prepare_feature_test_case_in_workspace(
            &test_options(root.clone()),
            &case,
            workspace.clone(),
        )
        .expect_err("library write should fail");

        assert!(!error.is_empty());
        let _ = fs::remove_dir_all(root);
        let _ = fs::remove_dir_all(workspace);
    }

    #[test]
    fn prepare_feature_test_case_reports_build_context_create_errors() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let workspace = crate::test_support::unique_temp_dir("feature-test-discovery-workspace");
        let test_dir = root.join("test").join("demo");
        fs::create_dir_all(&test_dir).expect("test dir");
        fs::create_dir_all(&workspace).expect("workspace");
        fs::write(workspace.join(".feature-test-build"), "not a directory")
            .expect("blocked build context");
        fs::write(test_dir.join("test.sh"), "#!/bin/sh\n").expect("script");
        let case = FeatureTestCase {
            name: "demo".to_string(),
            script_path: test_dir.join("test.sh"),
            execution: FeatureTestExecution::Autogenerated {
                feature: "demo".to_string(),
            },
        };

        let error = prepare_feature_test_case_in_workspace(
            &test_options(root.clone()),
            &case,
            workspace.clone(),
        )
        .expect_err("build context create should fail");

        assert!(!error.is_empty());
        let _ = fs::remove_dir_all(root);
        let _ = fs::remove_dir_all(workspace);
    }

    #[test]
    fn prepare_feature_test_case_reports_duplicate_manifest_parse_errors() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let feature_dir = root.join("src").join("demo");
        let test_dir = root.join("test").join("demo");
        fs::create_dir_all(&feature_dir).expect("feature dir");
        fs::create_dir_all(&test_dir).expect("test dir");
        fs::write(feature_dir.join("devcontainer-feature.json"), "{").expect("manifest");
        fs::write(test_dir.join("duplicate.sh"), "#!/bin/sh\n").expect("script");
        let case = FeatureTestCase {
            name: "demo duplicate".to_string(),
            script_path: test_dir.join("duplicate.sh"),
            execution: FeatureTestExecution::Duplicate {
                feature: "demo".to_string(),
            },
        };

        let error = prepare_feature_test_case(&test_options(root.clone()), &case)
            .expect_err("invalid manifest");

        assert!(!error.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn prepare_duplicate_feature_case_materializes_two_installations_and_exec_env() {
        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let workspace = crate::test_support::unique_temp_dir("feature-test-discovery-workspace");
        let feature_dir = root.join("src").join("demo");
        let test_dir = root.join("test").join("demo");
        fs::create_dir_all(&feature_dir).expect("feature dir");
        fs::create_dir_all(&test_dir).expect("test dir");
        fs::write(
            feature_dir.join("devcontainer-feature.json"),
            r#"{
  "id": "demo",
  "version": "1.0.0",
  "options": {
    "color": {
      "type": "string",
      "enum": ["blue", "green"],
      "default": "blue"
    }
  }
}"#,
        )
        .expect("manifest");
        fs::write(test_dir.join("duplicate.sh"), "#!/bin/sh\n").expect("script");
        let case = FeatureTestCase {
            name: "demo duplicate".to_string(),
            script_path: test_dir.join("duplicate.sh"),
            execution: FeatureTestExecution::Duplicate {
                feature: "demo".to_string(),
            },
        };

        let prepared = prepare_feature_test_case_in_workspace(
            &test_options(root.clone()),
            &case,
            workspace.clone(),
        )
        .expect("prepare duplicate case");

        assert_eq!(prepared.script_name, "duplicate.sh");
        assert_eq!(
            prepared.base_image,
            BaseImageSource::Image("debian:bookworm-slim".to_string())
        );
        assert_eq!(prepared.feature_installations.len(), 2);
        assert_eq!(
            prepared.feature_installations[0].source,
            FeatureInstallationSource::Local(feature_dir.clone())
        );
        assert_eq!(
            prepared.feature_installations[1].source,
            FeatureInstallationSource::Local(feature_dir)
        );
        assert!(prepared
            .exec_env
            .iter()
            .any(|(key, value)| key == "COLOR" && value == "green"));
        assert!(prepared
            .exec_env
            .iter()
            .any(|(key, value)| key == "COLOR__DEFAULT" && value == "blue"));
        let _ = fs::remove_dir_all(root);
        let _ = fs::remove_dir_all(workspace);
    }

    #[cfg(unix)]
    #[test]
    fn prepare_feature_test_case_reports_non_utf8_script_names() {
        use std::ffi::OsString;
        use std::os::unix::ffi::OsStringExt;

        let root = crate::test_support::unique_temp_dir("feature-test-discovery");
        let test_dir = root.join("test");
        fs::create_dir_all(&test_dir).expect("test dir");
        let invalid_name = OsString::from_vec(vec![0xff]);
        let case = FeatureTestCase {
            name: "invalid".to_string(),
            script_path: test_dir.join(invalid_name),
            execution: FeatureTestExecution::Scenario {
                scenario_dir: "invalid".to_string(),
                config: Value::Object(Default::default()),
            },
        };

        let error = prepare_feature_test_case(&test_options(root.clone()), &case)
            .expect_err("invalid path");

        assert!(error.contains("Invalid test script path:"), "{error}");
        let _ = fs::remove_dir_all(root);
    }
}
