//! Shared types and entrypoints for feature test subcommands.

mod discovery;
mod materialize;
mod runtime;

use std::path::PathBuf;

use serde_json::Value;

use crate::commands::common;

pub(super) use runtime::FeatureTestRuntime;

pub(super) const DEFAULT_FEATURE_TEST_BASE_IMAGE: &str = "docker.io/library/debian:bookworm-slim";
pub(super) const FEATURE_TEST_LIBRARY_SCRIPT_NAME: &str = "dev-container-features-test-lib";
pub(super) const FEATURE_TEST_LIBRARY_SCRIPT: &str = r#"#!/bin/bash
SCRIPT_FOLDER="$(cd "$(dirname $0)" && pwd)"
USERNAME=${1:-root}

if [ -z $HOME ]; then
    HOME="/root"
fi

FAILED=()

echoStderr()
{
    echo "$@" 1>&2
}

check() {
    LABEL=$1
    shift
    echo -e "\n"
    echo -e "🔄 Testing '$LABEL'"
    echo -e '\033[37m'
    if "$@"; then
        echo -e "\n"
        echo "✅  Passed '$LABEL'!"
        return 0
    else
        echo -e "\n"
        echoStderr "❌ $LABEL check failed."
        FAILED+=("$LABEL")
        return 1
    fi
}

checkMultiple() {
    PASSED=0
    LABEL="$1"
    echo -e "\n"
    echo -e "🔄 Testing '$LABEL'."
    shift; MINIMUMPASSED=$1
    shift; EXPRESSION="$1"
    while [ "$EXPRESSION" != "" ]; do
        if $EXPRESSION; then ((PASSED+=1)); fi
        shift; EXPRESSION=$1
    done
    if [ $PASSED -ge $MINIMUMPASSED ]; then
        echo -e "\n"
        echo "✅ Passed!"
        return 0
    else
        echo -e "\n"
        echoStderr "❌ '$LABEL' check failed."
        FAILED+=("$LABEL")
        return 1
    fi
}

reportResults() {
    if [ ${#FAILED[@]} -ne 0 ]; then
        echo -e "\n"
        echoStderr -e "💥  Failed tests: ${FAILED[@]}"
        exit 1
    else
        echo -e "\n"
        echo -e "Test Passed!"
        exit 0
    fi
}"#;

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct FeatureTestCase {
    pub(super) name: String,
    pub(super) script_path: PathBuf,
    pub(super) execution: FeatureTestExecution,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct FeatureTestResult {
    pub(super) name: String,
    pub(super) passed: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) enum FeatureTestExecution {
    Autogenerated { feature: String },
    Scenario { scenario_dir: String, config: Value },
    Duplicate { feature: String },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct FeatureTestOptions {
    pub(super) project_folder: PathBuf,
    pub(super) base_image: String,
    pub(super) remote_user: Option<String>,
    pub(super) preserve_test_containers: bool,
    pub(super) permit_randomization: bool,
    pub(super) quiet: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) enum BaseImageSource {
    Image(String),
    Build {
        dockerfile_path: PathBuf,
        context_path: PathBuf,
    },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) enum FeatureInstallationSource {
    Local(PathBuf),
    Published(String),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct FeatureInstallation {
    pub(super) source: FeatureInstallationSource,
    pub(super) env: Vec<(String, String)>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct PreparedFeatureTestCase {
    pub(super) name: String,
    pub(super) workspace_dir: PathBuf,
    pub(super) build_context_dir: PathBuf,
    pub(super) base_image: BaseImageSource,
    pub(super) script_name: String,
    pub(super) feature_installations: Vec<FeatureInstallation>,
    pub(super) exec_env: Vec<(String, String)>,
    pub(super) remote_user: Option<String>,
}

pub(super) fn run_features_test(args: &[String]) -> std::process::ExitCode {
    match execute_feature_tests(args) {
        Ok(results) => {
            if !common::has_flag(args, "--quiet") && !common::has_flag(args, "-q") {
                println!("  ================== TEST REPORT ==================");
                for result in &results {
                    let status = if result.passed {
                        "✅ Passed"
                    } else {
                        "❌ Failed"
                    };
                    println!("{status}:      '{}'", result.name);
                }
                if !common::has_flag(args, "--preserve-test-containers") {
                    println!("Cleaning up {} test containers", results.len());
                }
            }
            if results.iter().all(|result| result.passed) {
                std::process::ExitCode::SUCCESS
            } else {
                std::process::ExitCode::from(1)
            }
        }
        Err(error) => {
            eprintln!("{error}");
            std::process::ExitCode::from(1)
        }
    }
}

#[cfg(test)]
pub(super) fn discover_feature_test_scenarios(args: &[String]) -> Result<Vec<String>, String> {
    Ok(discovery::discover_feature_test_cases(args)?
        .into_iter()
        .map(|case| case.name)
        .collect())
}

fn execute_feature_tests(args: &[String]) -> Result<Vec<FeatureTestResult>, String> {
    let mut runtime = runtime::ContainerEngineFeatureTestRuntime;
    execute_feature_tests_with_runtime(args, &mut runtime)
}

pub(super) fn execute_feature_tests_with_runtime<R: FeatureTestRuntime>(
    args: &[String],
    runtime: &mut R,
) -> Result<Vec<FeatureTestResult>, String> {
    let options = parse_feature_test_options(args)?;
    let cases = discovery::discover_feature_test_cases(args)?;
    runtime::execute_feature_tests_with_runtime(args, runtime, &options, cases)
}

fn parse_feature_test_options(args: &[String]) -> Result<FeatureTestOptions, String> {
    let project_folder = common::parse_option_value(args, "--project-folder")
        .or_else(|| common::parse_option_value(args, "--projectFolder"))
        .or_else(|| args.iter().rev().find(|arg| !arg.starts_with('-')).cloned())
        .map(PathBuf::from)
        .ok_or_else(|| "features test requires a project folder".to_string())?;
    let base_image = common::parse_option_value(args, "--base-image")
        .unwrap_or_else(|| DEFAULT_FEATURE_TEST_BASE_IMAGE.to_string());
    let remote_user = common::parse_option_value(args, "--remote-user");
    let preserve_test_containers = common::has_flag(args, "--preserve-test-containers");
    let permit_randomization = common::has_flag(args, "--permit-randomization");
    let quiet = common::has_flag(args, "--quiet") || common::has_flag(args, "-q");
    Ok(FeatureTestOptions {
        project_folder,
        base_image,
        remote_user,
        preserve_test_containers,
        permit_randomization,
        quiet,
    })
}

#[cfg(test)]
mod tests {
    use super::{parse_feature_test_options, run_features_test, DEFAULT_FEATURE_TEST_BASE_IMAGE};

    #[test]
    fn feature_test_option_parsing_supports_aliases_and_defaults() {
        let options = parse_feature_test_options(&["/tmp/project".to_string()]).expect("options");
        assert_eq!(
            options.project_folder,
            std::path::PathBuf::from("/tmp/project")
        );
        assert_eq!(options.base_image, DEFAULT_FEATURE_TEST_BASE_IMAGE);
        assert_eq!(options.remote_user, None);
        assert!(!options.preserve_test_containers);
        assert!(!options.permit_randomization);
        assert!(!options.quiet);

        let options = parse_feature_test_options(&[
            "--projectFolder".to_string(),
            "/tmp/project".to_string(),
            "--base-image".to_string(),
            "ubuntu:24.04".to_string(),
            "--remote-user".to_string(),
            "vscode".to_string(),
            "--preserve-test-containers".to_string(),
            "--permit-randomization".to_string(),
            "-q".to_string(),
        ])
        .expect("aliased options");
        assert_eq!(options.base_image, "ubuntu:24.04");
        assert_eq!(options.remote_user.as_deref(), Some("vscode"));
        assert!(options.preserve_test_containers);
        assert!(options.permit_randomization);
        assert!(options.quiet);
    }

    #[test]
    fn run_features_test_reports_option_errors() {
        assert_eq!(run_features_test(&[]), std::process::ExitCode::from(1));
    }
}
